### ISSUE TITLE
ukol1

### ISSUE THREAD

**Issue by ghost** [parsley-classroom/kmi-web-l02t01#1]
V této nové mám problém s push origin, nabízí mi to jenom pull origin u kterého to píše unable to merge histories
@Thomasparsley

**Comment by Thomasparsley** [comment]
Poté co naklonujete repositář je potřeba přesunout do naklonovaného repositáře pouze soubory, které jsou potřebné pro splnění úkolu. Například `index.html` či `style.css`.

**Comment by ghost** [comment]
> 

jistě akorát mám problem s tím pushem, myslel jsem že když to znovu přijmu tak se historie vymaže ale to se nestalo
![správný](https://user-images.githubusercontent.com/100167465/158072023-20cf09ac-5b55-45f4-b033-bf1263bdd794.png)
![fetch](https://user-images.githubusercontent.com/100167465/158072035-f5d758c9-300a-4bf2-b54a-c1c39f724c98.png)

**Comment by Thomasparsley** [comment]
V úterý na cvičení to vyřešíme.
